(() => {
'use strict';
const cities=[
{name:'Delhi',state:'Delhi',region:'north',lat:28.6139,lon:77.209,aqi:289,pm25:178,pm10:252,no2:68},
{name:'Jaipur',state:'Rajasthan',region:'north',lat:26.9124,lon:75.7873,aqi:198,pm25:104,pm10:190,no2:43},
{name:'Lucknow',state:'Uttar Pradesh',region:'north',lat:26.8467,lon:80.9462,aqi:221,pm25:122,pm10:211,no2:52},
{name:'Chandigarh',state:'Chandigarh',region:'north',lat:30.7333,lon:76.7794,aqi:156,pm25:76,pm10:143,no2:35},
{name:'Srinagar',state:'Jammu & Kashmir',region:'north',lat:34.0837,lon:74.7973,aqi:92,pm25:39,pm10:82,no2:19},
{name:'Ahmedabad',state:'Gujarat',region:'west',lat:23.0225,lon:72.5714,aqi:164,pm25:81,pm10:157,no2:39},
{name:'Mumbai',state:'Maharashtra',region:'west',lat:19.076,lon:72.8777,aqi:133,pm25:61,pm10:128,no2:32},
{name:'Pune',state:'Maharashtra',region:'west',lat:18.5204,lon:73.8567,aqi:119,pm25:54,pm10:113,no2:27},
{name:'Bhopal',state:'Madhya Pradesh',region:'central',lat:23.2599,lon:77.4126,aqi:174,pm25:87,pm10:166,no2:40},
{name:'Kolkata',state:'West Bengal',region:'east',lat:22.5726,lon:88.3639,aqi:203,pm25:111,pm10:202,no2:48},
{name:'Patna',state:'Bihar',region:'east',lat:25.5941,lon:85.1376,aqi:218,pm25:119,pm10:207,no2:51},
{name:'Bhubaneswar',state:'Odisha',region:'east',lat:20.2961,lon:85.8245,aqi:127,pm25:58,pm10:121,no2:29},
{name:'Hyderabad',state:'Telangana',region:'south',lat:17.385,lon:78.4867,aqi:141,pm25:67,pm10:134,no2:33},
{name:'Bengaluru',state:'Karnataka',region:'south',lat:12.9716,lon:77.5946,aqi:108,pm25:48,pm10:104,no2:24},
{name:'Chennai',state:'Tamil Nadu',region:'south',lat:13.0827,lon:80.2707,aqi:126,pm25:57,pm10:119,no2:30},
{name:'Kochi',state:'Kerala',region:'south',lat:9.9312,lon:76.2673,aqi:78,pm25:32,pm10:72,no2:17}
];
const $=id=>document.getElementById(id); const state={selected:'Delhi',showAll:false,scenario:'baseline',map:null,markers:new Map()};
const sourceNames=['Traffic','Construction','Industrial','Road dust','Other sources'];
const colors=['#61d6c8','#83a9d2','#b49add','#e5b66c','#70839c'];
function value(c){return c[$('pollutant').value]}
function unit(){return $('pollutant').value==='aqi'?'AQI':'µg/m³'}
function status(v){return v<=50?'Good':v<=100?'Satisfactory':v<=150?'Moderate':v<=200?'Poor':'Severe'}
function color(v){return v<=50?'#5dd5a1':v<=100?'#e5d66b':v<=150?'#f4b35f':v<=200?'#f18b63':'#fa6879'}
function visible(){const r=$('viewMode').value;return cities.filter(c=>r==='national'||c.region===r)}
function adjusted(c){let factor=state.scenario==='winter'?(c.region==='north'?1.3:1.12):state.scenario==='dust'?(c.region==='west'||c.region==='north'?1.25:1.08):1;return {...c,aqi:Math.round(c.aqi*factor),pm25:Math.round(c.pm25*factor),pm10:Math.round(c.pm10*factor),no2:Math.round(c.no2*(state.scenario==='winter'?1.12:1))}}
function currentCities(){return cities.map(adjusted)}
function events(){return currentCities().filter(c=>c.aqi>=125).sort((a,b)=>b.aqi-a.aqi).map((c,i)=>({id:`VAYU-${String(i+1).padStart(3,'0')}`,city:c.name,time:`${String(8+i%12).padStart(2,'0')}:00`,level:c.aqi>220?'critical':c.aqi>175?'high':'moderate',value:c.aqi,source:sourceFor(c).name}))}
function sourceFor(c){let raw=state.scenario==='dust'?[.22,.15,.12,.35,.16]:state.scenario==='winter'?[.42,.12,.16,.08,.22]:[.36,.17,.12,.09,.26];let shift=(c.region==='north'&&state.scenario==='winter')?0.08:0;raw[0]+=shift;raw[4]-=shift;const total=raw.reduce((a,b)=>a+b,0);const probs=raw.map(x=>x/total);let ix=probs.indexOf(Math.max(...probs));return {probs,index:ix,name:sourceNames[ix],confidence:Math.round((.48+probs[ix]*.35)*100)}}
function evidence(c,s){return [`${s.name} has the highest illustrative model probability (${Math.round(s.probs[s.index]*100)}%).`,`Scenario: ${$('scenario').selectedOptions[0].text}; region: ${c.region}.`,`Pollutant reading: ${value(c)} ${unit()}.`,`Interpretation is a model signal, not proof of source causality.`]}
function updateMap(){if(!state.map)return;const list=visible().map(adjusted);state.markers.forEach(m=>state.map.removeLayer(m));state.markers.clear();list.forEach(c=>{const v=value(c),m=L.circleMarker([c.lat,c.lon],{radius:Math.max(7,Math.min(17,6+v/35)),color:'#dbe9f4',weight:1.4,fillColor:color(v),fillOpacity:.9}).addTo(state.map);m.bindTooltip(`<b>${c.name}</b><br>${v} ${unit()} · ${status(v)}<br><small>Illustrative data</small>`);m.on('click',()=>selectCity(c.name));state.markers.set(c.name,m)});$('mapCount').textContent=`${list.length} simulated sites`;if(!list.some(c=>c.name===state.selected))state.selected=list[0]?.name;selectCity(state.selected,false);if(list.length)state.map.fitBounds(L.latLngBounds(list.map(c=>[c.lat,c.lon])),{padding:[22,22],maxZoom:5})}
function selectCity(name,pan=true){const c=currentCities().find(x=>x.name===name);if(!c)return;state.selected=name;const v=value(c),s=sourceFor(c);$('selectedName').textContent=c.name;$('selectedMeta').textContent=`${c.state} · simulated station`;$('selectedValue').textContent=v;$('selectedUnit').textContent=unit();$('selectedStatus').textContent=status(v);$('selectedStatus').style.color=color(v);$('selectedColor').style.background=color(v);$('attributionSubtitle').textContent=`Selected location · ${c.name}`;$('confidenceBadge').textContent=`${s.confidence}% illustrative confidence`;$('primarySource').textContent=s.name;$('primaryDescription').textContent=`Model probability ${Math.round(s.probs[s.index]*100)}% · scenario-based estimate`;$('sourceBars').innerHTML=sourceNames.map((n,i)=>`<div class="bar-row"><div><span>${n}</span><strong>${Math.round(s.probs[i]*100)}%</strong></div><div class="bar-track"><i style="width:${s.probs[i]*100}%;background:${colors[i]}"></i></div></div>`).join('');$('evidenceList').innerHTML=evidence(c,s).map(t=>`<li>${t}</li>`).join('');$('dominantSource').textContent=s.name;$('dominantCaption').textContent=`${Math.round(s.probs[s.index]*100)}% probability · ${c.name}`;state.markers.get(name)?.setStyle({weight:3});if(pan&&state.map)state.map.panTo([c.lat,c.lon]);renderChart(c);renderEvents()}
function renderMetrics(){const list=visible().map(adjusted),avg=list.reduce((s,c)=>s+value(c),0)/Math.max(1,list.length),ev=events().filter(e=>list.some(c=>c.name===e.city));$('avgAqi').innerHTML=`${Math.round(avg)} <small>${unit()}</small>`;$('avgCaption').textContent=`Mean ${$('pollutant').selectedOptions[0].text} across ${list.length} locations`;$('cityCount').textContent=list.length;$('eventCount').textContent=ev.length;$('eventBreakdown').textContent=`${ev.filter(e=>e.level==='critical').length} critical · ${ev.filter(e=>e.level==='high').length} high · ${ev.filter(e=>e.level==='moderate').length} moderate`;$('navEventCount').textContent=ev.length}
function renderEvents(){const list=events().filter(e=>visible().some(c=>c.name===e.city));const shown=state.showAll?list:list.slice(0,5);$('eventList').innerHTML=shown.map(e=>`<button class="event-row" data-event="${e.city}" aria-label="Inspect ${e.city} event"><i class="event-mark event-${e.level}"></i><span class="event-main"><strong>${e.city}</strong><span>${e.id} · ${e.time} · ${e.source}</span></span><span class="event-value"><strong>${e.value}</strong><span>${unit()} · ${e.level}</span></span></button>`).join('')||'<p class="muted">No threshold events in this view.</p>';document.querySelectorAll('[data-event]').forEach(el=>el.addEventListener('click',()=>{selectCity(el.dataset.event);$('map-panel').scrollIntoView({behavior:'smooth',block:'start'})}));$('showAllEvents').textContent=state.showAll?'Show fewer':'Show all';}
function renderChart(c){const base=value(c),hist=Array.from({length:24},(_,i)=>Math.max(8,Math.round(base*(.72+.22*Math.sin(i*.57)+i*.008)))),future=Array.from({length:8},(_,i)=>Math.max(8,Math.round(hist[23]*(1-.025*i)+(state.scenario==='winter'?i*.8:0))));const all=hist.concat(future),W=720,H=205,L=38,R=12,T=12,B=24,max=Math.max(100,Math.ceil(Math.max(...all)*1.2/50)*50),x=i=>L+i/(all.length-1)*(W-L-R),y=v=>T+(max-v)/max*(H-T-B),path=a=>a.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');const ticks=Array.from({length:5},(_,i)=>Math.round(max*i/4));$('trendChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="Synthetic ${unit()} history and illustrative outlook">${ticks.map(v=>`<line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}" stroke="#26374b" stroke-dasharray="3 5"/><text x="${L-8}" y="${y(v)+3}" text-anchor="end" fill="#72839a" font-size="10">${v}</text>`).join('')}<path d="${path(hist)}" fill="none" stroke="#62d7d0" stroke-width="2.5"/><path d="${path(future.map((v,i)=>i===0?hist[23]:v))}" transform="translate(0 0)" fill="none" stroke="#b69bea" stroke-width="2.5" stroke-dasharray="6 5"/> <line x1="${x(23)}" y1="${T}" x2="${x(23)}" y2="${H-B}" stroke="#71819a" stroke-dasharray="3 4"/><text x="${x(23)+6}" y="${T+10}" fill="#a9b7c9" font-size="9">NOW</text></svg>`}
function initMap(){if(!window.L){$('indiaMap').innerHTML='<div class="map-fallback">Map library could not load. Check your internet connection and reload.</div>';return}state.map=L.map('indiaMap',{scrollWheelZoom:false}).setView([22.8,79.2],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:18}).addTo(state.map);fetch('https://raw.githubusercontent.com/geohacker/india/master/state/india_state.geojson').then(r=>{if(!r.ok)throw Error('Boundary unavailable');return r.json()}).then(g=>L.geoJSON(g,{style:{color:'#5b8296',weight:1.1,fillColor:'#18334a',fillOpacity:.24}}).addTo(state.map).bringToBack()).catch(()=>{});updateMap()}
function refresh(){state.scenario=$('scenario').value;renderMetrics();updateMap();$('updatedAt').textContent=new Date().toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});$('refreshBtn').classList.remove('spinning')}
$('pollutant').addEventListener('change',refresh);$('viewMode').addEventListener('change',refresh);$('scenario').addEventListener('change',refresh);$('resetMap').addEventListener('click',()=>{$('viewMode').value='national';$('pollutant').value='aqi';$('scenario').value='baseline';state.showAll=false;state.selected='Delhi';refresh();if(state.map)state.map.setView([22.8,79.2],4)});$('refreshBtn').addEventListener('click',refresh);$('showAllEvents').addEventListener('click',()=>{state.showAll=!state.showAll;renderEvents()});
initMap();refresh();
})();